### ISSUE TITLE
Omitting the dist folder from git tracking

### ISSUE THREAD

**Issue by amerllica** [rssr-org/RSSR#2]
Actually, by the formal git folder architecture, putting and tracking the dist or build folder in the project is not a proper way. I guess in the near future it should be omitted.

**Comment by ebrahimiaval** [comment]
Probably this will happen, but now i need this folder to teach RSSR team. 

NOTE: At now RSSR is a public repository but we use it like private repository and advertise it after forming the RSSR team.
