### ISSUE TITLE
Using CSS modules instead of constant class names

### ISSUE THREAD

**Issue by amerllica** [rssr-org/RSSR#3]
Surly, using `import someScssFile.scss` inside each component, and putting them beside the main component is a proper way. But there is a better way to have hashed, compressed ugly class names and definitely the CSS modules way can help to have a lightweight bundle. Just like below:

```
import styles from 'someScssFile.scss';

~~~

<div className={styles.blockName_elemName_modName_modVal} />
```

And then after a build, for example in webpack we have a 5 lengths hashed name, then we could have:

```
<div class="_D4fdr"></div>
```

All class names with each length turn to 5 lengths and we will have a more compressed CSS bundle.

I guess this config could be in the near future.

**Comment by ebrahimiaval** [comment]
RSSR is not a framework with strict commands and rules so anyone can use their own structure. you can fork RSSR and use your structure.
