### ISSUE TITLE
NODE_ENV

### ISSUE THREAD

**Issue by FazelMahdi** [rssr-org/RSSR#4]
fix to "dev": "NODE_ENV=development & node --max_old_space_size=8000 ./provider/server/development.js",

**Comment by ebrahimiaval** [comment]
what is the problem?
Give more description, your description is meaningless.

**Comment by FazelMahdi** [comment]
while running npm run dev this error appear:
'NODE_ENV' is not recognized as an internal or external command, operable program or batch file.
it needs some changes like cross-env or something else.

**Comment by ebrahimiaval** [comment]
Fixed issue in new changes.

but in previous version  and in Windows you must use win-node-env package (https://github.com/laggingreflex/win-node-env)
